
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import NavBar from "@/components/NavBar/NavBar";
import {ThemeContextProvider} from "@/context/ThemeContext";
import ThemeProviders from "@/providers/ThemeProviders";
import {getServerSession} from "next-auth";
import SessionProvider from "@/providers/SessionProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {

    const session = await getServerSession()

    return (
        <html lang='en' className='h-full'>
            <body className={cn('relative h-full font-sans antialiased', inter.className)}>
                <SessionProvider session={session}>
                    <ThemeContextProvider>
                        <ThemeProviders>
                            <main className='containers relative flex flex-col min-h-screen'>
                                <NavBar />
                                <div className='flex-grow flex-1'>
                                    {children}
                                </div>
                                <h1>FOOTER</h1>
                            </main>
                        </ThemeProviders>
                    </ThemeContextProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
